### ISSUE TITLE
Feature Request: Method to backup and restore node configuration

### ISSUE THREAD

**Issue by ggee** [manu-fwi/RR-duino#1]
If we have a hardware failure of an Arduino, it would be nice to be able to upload the config to the replacement node after the address has been assigned.

With that, a mechanism to save a nodes config to a file.

**Comment by manu-fwi** [comment]
This could be added to the setup script?

**Comment by manu-fwi** [comment]
You can test the setup script now.

**Comment by ggee** [comment]
I tried backup so far.  Works as expected.

**Comment by manu-fwi** [comment]
OK thanks, I close it then.
